### ISSUE TITLE
Add support for Mappings in Tasks files

### ISSUE THREAD

**Issue by rene84** [org-formation/org-formation-cli#102]
Similar to CloudFormation templates, I would like to be able to define and use Mappings and !FindInMap / Fn::FindInMap inside tasks files.

The primary use-case is to use a tasks file that re-uses the same template multiple times and that tasks file is itself called by a parent tasks file as type: Include.

I will then want to parameterise the execution of the templates along 2 dimensions, which is best solved with a map.

Example:
We are exposing 20 microservices through individual API gateways. We would like to use a single serverless project. That serverless project is parameterized with an IP address target for the DNS name for the service combined with an environment tag (which is concatenated to the DNS name).

We define tasks file1: org-formation-tasks.yml, which calls api-gateways.yml 4 times, with a parameter dev,tst,acc and prd.

Within api-gateways.yml there are 20 calls to the serverless project and the IP addresses are fetched from a Map using !FindInMap like so:

  Mappings: 
    MyDnsMap:
      service1: 
        dev: 12.34.56.78
        tst: 12.34.56.79
      service2: 
        dev: 12.34.56.71
        tst: 12.34.56.72
      service3:
        dev: 12.34.56.73
        tst: 12.34.56.74

**Comment by OlafConijn** [comment]
fixed in v0.9.12
