### ISSUE TITLE
Have validate-tasks gracefully exit when accounts are added to the org

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#106]
If an account is added to the organization there are a number of cases in which `validate-tasks` will fail. an example is registering a custom type and using the registered type in an `update-stack` task later on. As validate-tasks doesnt register the type validating the template will fail.

Proposed solution is to exit gracefully with a printed warning in order for CI on the branch not to fail and block merging changes.

**Comment by shortjared** [comment]
This worked for us!

**Comment by OlafConijn** [comment]
fixed in v0.9.12
