### ISSUE TITLE
bug: Template with !ReadFile will not redeploy if included file changed

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#121]
the reason is that the hash used for comparison doesnt look at the file being included.

**Comment by shortjared** [comment]
We just got bit by this. Ouch.

**Comment by OlafConijn** [comment]
> We just got bit by this. Ouch.
> 


Meh, for now you can 
1) set ForceDeploy to true. 
2) change something like the description of the stack when updating the source (forces the hash to be changed)
3) upload the code to s3 using copy-to-s3 and make the hash part of the s3 path.

Planning to fix this within days.
