### ISSUE TITLE
Delegate dynamic references resolution to CloudFormation

### ISSUE THREAD

**Issue by eduardomourar** [org-formation/org-formation-cli#129]
For [dynamic references](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html), if you change its value OrgFormation will simply skip it. It would nice if they can be forcefully deployed every time (therefore delegating its resolution to CloudFormation). Then, the user could set `ForceDeploy: false` in case they don't want that behavior.

**Comment by OlafConijn** [comment]
in commit: https://github.com/org-formation/org-formation-cli/pull/115/commits/2a530b91358d4dc554b774c7c4b333dce6c84b96.
still needs nesting, obviously
