### ISSUE TITLE
Publish organization.yml to S3 after change and raise eventbridge event

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#130]
Sometimes other tasks/build processes depend on information from the organization.yml. putting all these build processes in the same pipeline does not scale well. besides not all build processes might run org-formation. Therefore it would be nice to:

- After changes to the organization.yml have been made and the main build has successfully ran and
  1. upload the organization.yml to s3 (to the state bucket)
  2. emit an event using eventBridge that can be caught to execute a secondary build
- Have a library in nodejs that allows a buildprocess (e.g. using CDK) to parse the organization.yml

An alternative could be to depend on eventbridge events from the AWS.Organizations service and query the organizations api for account data. there is two issues with this approach:
1. it requires a process to assumeRole into the master account.
2. it would be quite a puzzle to sort out all the right events (some are not covered by eventBridge like changes to account Alias) and querying all the right information from the organizations api would also require a bit of work.

new features provided by the eventBridge team allow events to be sourced from a different account. see: https://aws.amazon.com/blogs/compute/simplifying-cross-account-access-with-amazon-eventbridge-resource-policies/

**Comment by shortjared** [comment]
I think us emitting the event is preferable. I’m hesitant to depend on something you say all the functionality isn’t there for. We’d end up duct taping around things that’d be desirable and easier if we just emitted our own clean events.

Tell me more about the lib (you said nodejs, I assume you mean TypScript?). Would this be something we’d use in just our substrate processes, across substrate projects, or across Stedi in general?

I do see tremendous value in breaking up our processes. Substrate repo takes a LONG time for trivial changes.

**Comment by OlafConijn** [comment]
nice, thanks @shortjared!
doing another cycle on the entire thing....

the event would look like the following:
``` yaml
  source: 'oc.org-formation',
  detailType: 'events.org-formation.com',
  detail: 
    eventName: 'OrganizationUpdate',
    s3key: 'organization.yml',
    s3bucket: 'organization-formation-123123123123'
```

The lib/parser would indeed be typescript.

It would take information form the event (and the file it references) and return an object model that contains all accounts, organizational units, scps, tags and the references between these elements. This maps pretty well to the contents of [/src/parser/](https://github.com/org-formation/org-formation-cli/tree/master/src/parser).

The output of the parser would (without modification) allow you to traverse the organization structure: 
``` js
const unit = template.organizationSection.organizationalUnits.find(x=>x.organizationalUnitName == 'my-unit');
console.log('ids nested units:' + unit.organizationalUnits.map(x=>x.PhysicalId).join(', '));
console.log('ids child accounts:' + unit.accounts.map(x=>x.PhysicalId).join(', '));
console.log('logical names (from template) of accounts:' + unit.accounts.map(x=>x.TemplateResource.logicalId).join(', '));
```

the interface for account looks like the following:

The output of the parser would also allow the caller to evaluate a binding:
``` js
const accountIds = template.resolveNormalizedLogicalAccountIds
```

The lib could be used in any (build) process that depends on the information within this file.
