### ISSUE TITLE
org-formation is not granting CAPABILITY_AUTO_EXPAND

### ISSUE THREAD

**Issue by hanninen** [org-formation/org-formation-cli#135]
I am trying to provision the Datadog integration templates through `org-formation`, but the `org-formation update-stacks` call fails  due to error message `Requires capabilities : [CAPABILITY_AUTO_EXPAND]`.

The `CAPABILITY_AUTO_EXPAND` is required by the CloudFormation macro that Datadog provisions as part of their integration.

This should be a configuration parameter and a command line parameter, so that during `update-stacks` or `perform-stacks` calls I could grant the needed capability.

The template can be found https://github.com/DataDog/cloudformation-template/tree/master/aws

**Comment by OlafConijn** [comment]
This is fixed in `0.9.14-beta.6`. its a beta but stable

There is 1 point of regression that has to do calling `validate-tasks` on a task file that references an org-file where a new account was added. validation might fail worst case.

**Comment by hanninen** [comment]
Thanks @OlafConijn , I'll give the beta a test run!
