### ISSUE TITLE
Create org-formation client library

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#144]
It is currently (as of v0.9.14) possible to split the org-formation build in multiple smaller build processes.

Sometimes, there is a requirement to resolve lists of account ids or metadata about these accounts at runtime (lambda?) or from within another build process (CDK?).

Concrete scenarios include:
- Generating least privilege IAM policies for cross account access (e.g. using CDK)
- Translating account ids to account names when reporting/logging information from different source accounts (e.g. using Lambda).

org-formation-client will be published in npm as `aws-organization-formation-client` and implemented as typescript library.
The implementation will be very much like any other AWS SDK and will, e.g. allow for credentials to be passed in the constructor. there will then be passed to the underlying aws service client libraries.

todo: evaluate the aws clients v3

how to create an instance of the org formation client:
``` js
const orgClient = new OrgFormationClient( {  
    credentials : myCrendialsProvider.resolve(), // works just like any other aws service
    stateBucketName: 'my-state-bucket-name', // default will be organization-formation-${MasterAccountId}
    stateObjectKey: 'state.json', // this is also the default
    organizationObjectKey: 'organization.yml', // this is also the default
})
```

how to enumerate account ids
``` js
const developmentOUBinding: IOrganizationBinding = { OrganizationalUnit: { Ref: 'DevelopmentOU' } };
const developmentOUAccountIds: string[] = orgClient.enumerateAccountIds(developmentOUBinding);

const moreComplexBinding: IOrganizationBinding = { IncludeMasterAccount: true, Account: '*', ExcludeAccount: [ { Ref: 'AccountB' } ] };
const moreComplexAccountIds: string[] = orgClient.enumerateAccountIds(moreComplexBinding);
```

how to retrieve metadata related to an account:
``` js

const account = orgClient.getAccount('1223123123123');
console.log(account.logicalId);
console.log(account.accountName);
console.log(account.alias);
console.log(account.rootEmail);
console.log(account.tags);
//etc

```

**Comment by eduardomourar** [comment]
It will be awesome. For a lambda, this will works perfectly. For CDK, I believe this would have to used either as a custom resource or resource type (obviously backed by a lambda) so that you can use the account details within a cloudformation template.

**Comment by OlafConijn** [comment]
boom! https://github.com/org-formation/org-formation-client
i think this would cover the first 2 usecases :)

as for the CDK usecase, i would expect the library to be usable from the CDK code itself, e.g. create a cloudformation resource/cdk construct for each account in the org using a for-loop.
