### ISSUE TITLE
feature: reference template files with a URI

### ISSUE THREAD

**Issue by zaro0508** [org-formation/org-formation-cli#152]
We typically like to keep our cloudformation templates in a separate github repository so we can version them separately from our CI files.   We also deploy our CFN templates to an S3 bucket which gives us a central repository of versioned cloudformation templates that we can reference using a S3 or https URI.  It looks like org-formation expects all file references to be relative to the task file and in the local directory.  Instead of referencing the files in the local directory it would be great if we could reference them directly using a S3 bucket or github URI.

for example instead of `Template: ./password-policy.yaml` I would like to reference my templates :

* `Template: s3://my-repository-bucket/cfn-templates/v1.0.0/password-policy.yaml`
* `Template: https://raw.githubusercontent.com/zaro0508/cfn-templates/v1.0.0/password-policy.yaml`

or maybe the [`!ReadFile`](https://github.com/org-formation/org-formation-cli/blob/master/docs/task-files.md#readfile) function can be expanded to include URI references?

* `Template: !ReadFile s3://my-repository-bucket/cfn-templates/v1.0.0/password-policy.yaml`
* `Template: !ReadFile https://raw.githubusercontent.com/zaro0508/cfn-templates/v1.0.0/password-policy.yaml`

**Comment by OlafConijn** [comment]
hi! i was thinking about this feature a bit...

I think there is two distinct things above:
1) the reference to the template of an update-stacks command  (Template: ./mytemplate.yml), which provides the update-stacks command with a location on where it can find the right template to deploy.
2) the !ReadFile function, which reads the contents of a file and returns the contents as an string

If i understand your intent, you would like to deploy cloudformation templates that are hosted on s3 or http.
The syntax for this would be something like the following:

https://github.com/org-formation/org-formation-cli/blob/d688876991253478352ffdccddf9d91de35537d1/test/integration-tests/resources/scenario-non-local-templates/0-tasks.yml#L19

I have gone ahead and started a branch for this.

**Comment by zaro0508** [comment]
thanks for the that branch @OlafConijn.  If I understand correctly, your branch indicates to me that `!ReadFile` cannot be used with `Template:` as I've proposed in the doc update in this PR?  Also, is this PR still valid for `!ReadFile` usage with `Properties:`?
