### ISSUE TITLE
bug: org-formation init-pipeline - Stack fails to deploy 

### ISSUE THREAD

**Issue by TechnoNerdDad** [org-formation/org-formation-cli#161]
Running org-formation-cli v0.9.14 on NodeJS 15.6.0 on Ubuntu Server 20.04.x. Process starts out great but ends with the cli error:
```
ERROR: unable to create stack organization-formation-build in account 281838181670, region us-east-1, err: ResourceNotReady: Resource is not in the state stackCreateComplete
```

Investigation into the stack deploy events I find for the `OrgRepo` logical resource:
```
Code supplied is not a valid .zip archive
```

Upon downloading the `initial-commit.zip` from S3 and unzipping with 7-zip I observe these errors:
```
CRC failed : buildspec.yml
CRC failed : organization.yml
CRC failed : organization-parameters.yml
CRC failed : 000-organziation-build\organization-tasks.yml
CRC failed : 000-organziation-build\org-formation-build.yml
```

**Comment by OlafConijn** [comment]
hi! that sounds rather disappointing... 

i think you have ran into the following issue: https://github.com/archiverjs/node-archiver/issues/491
maybe try running that specific command on a different node version? 

curious to know whether that solves it. 
thanks!

**Comment by TechnoNerdDad** [comment]
Thank you for your prompt response and also your work on this fantastic tool!

Ah, I totally missed that in my research. Thanks for pointing to that. I have run the same org-formation command successfully with NodeJS 15.5.0!

**Comment by hilem** [comment]
Am I right in reading that the thread linked above implies the latest NodeJS 15 will work but not 16 or above?

**Comment by hilem** [comment]
I think the crc lib is referencing the old buggy version still. For context, I'm having the same issue as above with multiple NodeJS 16.x versions. NodeJS 15 doesn't have an arm build for OSX so I haven't tried that yet.

https://github.com/serverless/serverless/issues/8772#issuecomment-825698908

**Comment by luis-echegaray** [comment]
reproduced the issue on m1 mac running node 16


```org-formation init-pipeline organization.yml  --region us-east-1 --profile default``` -> FAILED in cloudformation with the same error in OP

Downgraded node to 15, and it ran fine
