### ISSUE TITLE
Unable to deploy SAM template with Globals property

### ISSUE THREAD

**Issue by eduardomourar** [org-formation/org-formation-cli#180]
Whenever deploying a SAM template that contains the Globals property, we get the following error:

> ERROR: Task Connector execute failed. reason: unable to load file template.yml. 
reason: unexpected attribute Globals found on template root. expected attributes are AWSTemplateFormatVersion, Description, Organization, OrganizationBinding, DefaultOrganizationBinding, OrganizationBindings, DefaultOrganizationBindingRegion, OrganizationBindingRegion, Metadata, Parameters, Mappings, Conditions, Resources, Outputs, Transform.

Running org-formation v0.9.15-beta.6.

**Comment by OlafConijn** [comment]
great! thanks.

**Comment by eduardomourar** [comment]
i have tested with commit https://github.com/org-formation/org-formation-cli/commit/2fdc1c7242a80425e4fe179e479a15de1a11f1f6 and it works. thanks!

**Comment by OlafConijn** [comment]
great, closing this as.
