### ISSUE TITLE
State does not save parameter value of type list 

### ISSUE THREAD

**Issue by eduardomourar** [org-formation/org-formation-cli#182]
Whenever we use a template that needs a list of strings (like [this one](https://github.com/org-formation/org-formation-reference/blob/eb82b1e381de32feadcc9571f92ca206bd0802dd/src/templates/100-aws-sso/_tasks.yml#L151)), the state being saved does not contain the values from the parameter. Whenever we update those values, OrgFormation will not trigger an update.

By running `org-formation print-tasks`, we see that the result does not have any value for the parameter:
```json
  {
    "ParameterKey": "managedPolicies"
  }
```
Running org-formation v0.9.15-beta.6

**Comment by OlafConijn** [comment]
i think this would work if the value is a comma separated list. 
the parameter datatype only allows for string: https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Parameter.html

i think two things could be improved here:
- auto convert the [] to a comma separated list
- apparently some sort of validation is not happening. using a value that is not expected { foo: 2} should result in an error

**Comment by eduardomourar** [comment]
I tried with `CommaSeparatedList` and `List<String>`, and both had the same error.

**Comment by eduardomourar** [comment]
A workaround was to use the Join function with comma in the task file.

**Comment by OlafConijn** [comment]
Indeed, modifying the parameter types does not do anything for how the parameters are passed. Should it? Maybe as an additional validation I guess it wouldn't hurt.


Parameters passed to cfn are always string. I'll write fix for the []=>string conversion shortly

**Comment by OlafConijn** [comment]
right, i think i misinterpreted the issue... the array does get passed properly, but when calculating the hash for comparison it does not (hash doesnt change => update does not happen). that right?

**Comment by eduardomourar** [comment]
Exactly right

**Comment by OlafConijn** [comment]
i believe this should work in `npm i aws-organization-formation@0.9.15-beta.8`. could you let me know? thanks!

**Comment by OlafConijn** [comment]
assume this to work
