### ISSUE TITLE
cannot deploy a single template to org-formation controlled accounts

### ISSUE THREAD

**Issue by zaro0508** [org-formation/org-formation-cli#195]
i’m testing my new template and I would like to use orgf to deploy it to my account however there doesn't seem to be a way to deploy just one template to an account.  i'm using orgf ver 0.9.14 and node ver 15.5.1

This didn’t seem to work for me..

```
npx org-formation update-stacks 900-testing/orgf-noop.yaml --profile testitorgmgnt-CiServiceRole --stack-name orgf-noop
ERROR: unable to load file 900-testing/orgf-noop.yaml.
reason: Top level Organization attribute is missing.
npm ERR! code 1
npm ERR! path /Users/zaro0508/work-sage/testitorgmgnt-infra/org-formation
npm ERR! command failed
npm ERR! command sh -c org-formation update-stacks 900-testing/orgf-noop.yaml --profile testitorgmgnt-CiServiceRole --stack-name orgf-noop

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zaro0508/.npm/_logs/2021-02-08T23_22_01_049Z-debug.log
```

The error seems to indicate that update-stacks needs to know about the accounts to deploy to, which is defined in a separate organization.yaml.  However there's no way to tell update-stacks about the accounts because the update-stacks command does not have an  `--organization-file` flag.

**Comment by zaro0508** [comment]
I've also tried setting org `organizationFile = ./organization.yaml` in a [.org-formationrc file](https://github.com/org-formation/org-formation-cli/blob/master/docs/cli-reference.md#runtime-configuration-org-formationrc) however that didn't work either.  I get the following error..
```
ERROR: unable to load file 900-testing/orgf-noop.yaml.
reason: Resource touchNothing is missing OrganizationBinding attribute and no top level OrganizationBinding found..
```

**Comment by OlafConijn** [comment]
hi @zaro0508 , setting the organization file through the .org-formationrc did work. 

You just ran into the next missing piece.... in order for org-formation to deploy a template it needs to know where to. 

For CloudFormation the answer to this question is easy: it is always the current account and region. 
For OrgFormation it could be any number of regions/accounts, the set of regions/accounts is determined using an OrganizationBinding (e.g. AccountsWithTag: 'mytag' + Region: [us-east-2, eu-west-1]) and the organization file that lists all accounts and account structure. This is the reason you need to have both.

You probably have specified these bindings using tasks but you can also specify them on every single resource in your template or as a toplevel attribute where it becomes a default.

If you are deploying a template to the current account and current region i think you should probably be using the aws cli `aws cloudformation create-stack` command. I don't think OrgFormation should be a replacement for functions implemented in cloudformation.

I did create a PR to support adding the organization-file as an option.
I am not sure whether it makes sense to add default organization bindings over the commandline. i'll leave that for a different day :).

**Comment by zaro0508** [comment]
> You probably have specified these bindings using tasks but you can also specify them on every single resource in your template or as a toplevel attribute where it becomes a default.

Yes, that is what i did.  here is my ofn file 
<details>
<summary>organizations-task.yaml</summary>
Orgf-Noop:
  Type: update-stacks
  Template: ./orgf-noop.yaml
  StackName: orgf-noop
  Parameters:
    ParamA: "bar"
  MaxConcurrentStacks: 10
  DefaultOrganizationBinding:
    IncludeMasterAccount: false
    Account: !Ref MemberXAccount
    Region: us-east-1
</details>

> If you are deploying a template to the current account and current region i think you should probably be using the aws cli aws cloudformation create-stack command. I don't think OrgFormation should be a replacement for functions implemented in cloudformation.

My goal is to test my template running in context of ofn because i want to make sure my CI/CD will run it successfully after I merge the file.   I can't do that using the AWS cloudformation CLI.  What would suggest as a test scenario i should use to accomplish my goal?

**Comment by OlafConijn** [comment]
@zaro0508 i just noticed me merging a PR closed this issue. had not read you comment above yet.

what i typically do/ recommend on PR builds is the follwing:
1. run the validate-tasks command against the main task file. this will do checks on on org-formation as well as run validate-stack on cloudformation with the output of transformation.
2. run print-tasks and then run cfn-lint on the output. this will catch a lot of things that ofn, neither cfn, would catch.



what i typically use (codepipeline buildspec) is:
``` yaml
version: 0.2
phases:
  install:
    commands:
      - npm ci
      - echo installed dependencies
      - npx org-formation -v
      - pip install cfn-lint
  build:
    commands:
      - npm run print-tasks -- --no-color
      - npm run validate-tasks -- --no-color
      - npm run cfn-lint
```

and the following are the scripts from package.json
``` json
{
    "print-tasks": "npx org-formation print-tasks ./src/_tasks.yml --output yaml --max-concurrent-stacks 100 --max-concurrent-tasks 100",
    "perform-tasks": "npx org-formation perform-tasks ./src/_tasks.yml --max-concurrent-stacks 50 --max-concurrent-tasks 1",
    "validate-tasks": "npx org-formation validate-tasks ./src/_tasks.yml --failed-tasks-tolerance 0  --max-concurrent-stacks 100 --max-concurrent-tasks 100",
    "cfn-lint": "cfn-lint ./.printed-stacks/**/*.yaml -i W2001,E3001,E1019,W1020,W2509,E3021"
    }

```
