### ISSUE TITLE
Feature: Allow buckets other than just community-resource-provider-catalog to be used for registering types

### ISSUE THREAD

**Issue by aaronosb** [org-formation/org-formation-cli#233]
### Allow buckets other than just community-resource-provider-catalog to be used for registering types
We have custom resource providers that are uploaded to an internally managed S3 and would like to be be able to use org formation to register-type for those resources. But currently the only bucket that can be used with register-type is community-resource-provider-catalog and will otherwise throw an error https://github.com/org-formation/org-formation-cli/blob/1ae7efea497754c49bca5d5510dff50d1ddb7670/src/plugin/impl/rp-build-task-plugin.ts#L139. It would be great if we could specify additional buckets to allow resource types to be registered from.

**Comment by eduardomourar** [comment]
As a workaround, you could just use the native cloudformation resource to actually register the type: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-resourceversion.html
