### ISSUE TITLE
Use main branch instead of master

### ISSUE THREAD

**Issue by leantorres73** [org-formation/org-formation-cli#234]
### Subject of the issue
Not sure if calling it issue or enhancement. 
Amazon is moving away from branch `master`, instead it's using `main`.

![image](https://user-images.githubusercontent.com/12806363/113418618-3cd97e80-939c-11eb-9800-1ccf563adab2.png)

I've just ran init-pipeline command, and the pipeline is listening the `master` branch but the codecommit is created in the `main` branch.
Of course it's really simple to change branch and push, but it would be more organized for the tool that both, codepipeline and codecommit, are created and listening to the same branch.

### Your environment
* version of org-formation: 0.9.14
* version of node: v12.21.0
* which OS/distro: Linux Mint

### Steps to reproduce
You just need to run init-pipeline command.

### Expected behaviour

You can set the default branch name or change the pipeline to use main instead.

https://aws.amazon.com/es/premiumsupport/knowledge-center/codecommit-branch-name-cloudformation/

### Actual behaviour

Pipeline listening to master branch, codecommit created in main branch

**Comment by OlafConijn** [comment]
thanks! fixed in release v0.9.15
