### ISSUE TITLE
Support setting arbitrary definitions in ofn files

### ISSUE THREAD

**Issue by zaro0508** [org-formation/org-formation-cli#254]
### Subject of the issue
i would like to define a default set of tags in my organizations.yaml file then reference them in all my accounts.  I attempted to use yaml anchors and aliases to accomplish this use case however it doesn't seem to work because ofn does not support adding arbitrary top level definitions.  It would be great if ofn could support arbitrary top level definitions or at least a specific `Definitions` attribute in ofn files.

here’s an example of how it could work:

<details>
<summary>organization.yaml</summary>

    AWSTemplateFormatVersion: '2010-09-09-OC'
    Description: Test org
    Definitions
      # default tags
      Tags: &tags
        Department: Platform
        Project: Infrastructure
        CloudwatchCloudTrailLogRetentionPeriod: 90
    Organization:
      MasterAccount:
        Type: OC::ORG::MasterAccount
        Properties:
          AccountName: organizations
          RootEmail: organizations@acme.org
          Alias: org-acme-organizations
          Tags:
            <<: *tags
            CloudwatchCloudTrailLogRetentionPeriod: 365   # override default tag
      ITSandboxAccount:
        Type: OC::ORG::Account
        Properties:
          AccountName: itsandbox
          RootEmail: itsandbox@acme.org
          Alias: org-acme-itsandbox
          Tags:
            <<: *tags

</details>

### Your environment
* ofn version 0.9.16
* node version v15.5.1 
* MAC 10.14.6

**Comment by OlafConijn** [comment]
Nice, I think this would be great for org, task and template files
