### ISSUE TITLE
org-formation init does not honor --cross-account-role-name

### ISSUE THREAD

**Issue by BigAl** [org-formation/org-formation-cli#266]
### org-formation init does not honor --cross-account-role-name
During initialization the --cross-account-role-name switch is ignored and instead `OrganizationAccountAccessRole` is used

### Your environment
* org-formation 0.9.16
* Node v14.17.0
* MacOSX

### Steps to reproduce
init organization.yml --cross-account-role-name myOrgAdmin --region ap-southeast-2

### Expected behaviour
With `myOrgAdmin` role correctly defined  in an account  there should be no warning of login failures

### Actual behaviour

```
WARN: AccessDenied: unable to log into account 12345678901. This might have various causes, to troubleshoot:
https://github.com/OlafConijn/AwsOrganizationFormation/blob/master/docs/access-denied.md
````

**Comment by OlafConijn** [comment]
right! that's unfortunate - will get back to you on this soon

**Comment by BigAl** [comment]
My coding skills were not good enough be able to follow the code flow fully. I got as far as line 301 in `aws-organization-reader.ts` I was able to confirm with Console Log statement that the role is always `OrganizationAccountAccessRole`

```
 const targetRoleConfig = await GetOrganizationAccessRoleInTargetAccount(that.crossAccountConfig, accountId);
 ConsoleUtil.LogInfo(`Role: ${targetRoleConfig.role}`);
```

**Comment by OlafConijn** [comment]
hi @BigAl  - thanks for posting this here. i created a beta in which the issue should be fixed.  `npm i aws-organization-formation@0.9.17-beta.15`

good luck!

**Comment by BigAl** [comment]
Thanks for that quick turnaround I can confirm that it now works as expected.
