### ISSUE TITLE
Support for "AI services opt-out policies"

### ISSUE THREAD

**Issue by GrahamCampbell** [org-formation/org-formation-cli#296]
Is it possible to IaC AI services opt-out policies on orgs using this tool. If not, is it something you'd consider adding/helping me to add?

**Comment by eduardomourar** [comment]
Yes, there is support for it. You can find an example here: https://github.com/org-formation/org-formation-reference/blob/master/src/templates/020-secure-defaults/organization-policies.yml

**Comment by GrahamCampbell** [comment]
Awesome, thank you!. :)
