### ISSUE TITLE
Unable to render features.pdf

### ISSUE THREAD

**Issue by T-Nik** [org-formation/org-formation-cli#401]
### Subject of the issue
Following the link from: 
_Want more? here a [list of 50+ features](https://github.com/org-formation/org-formation-cli/blob/master/docs/features.pdf) 😎😎😎_

I do not get the list. 

### Your environment
Safari

### Steps to reproduce
Go to https://github.com/org-formation/org-formation-cli/blob/master/docs/features.pdf

### Expected behaviour
Getting a list with 50+ features of org-formation

### Actual behaviour
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/107757730/181930355-0a7a8651-c451-4441-95f7-868274051c32.png">

**Comment by yannickvr** [comment]
Wasn't this just something Github didn't support at the time? Currently it works fine in Edge and Firefox:

![image](https://user-images.githubusercontent.com/4091308/222896600-f9e77b19-eb27-47ab-8f47-97bef945255d.png)
