### ISSUE TITLE
.orgformation-rc file

### ISSUE THREAD

**Issue by OlafConijn** [org-formation/org-formation-cli#47]
Would be cool to have a .orgformation-rc (.orgfo-rc? .org-rc?) file that contains runtime configuration such as `profile`, `stateBucketName`, `stateObject` options.

**Comment by craighurley** [comment]
Should region be taken from the profile?

**Comment by OlafConijn** [comment]
@craighurley yeah, makes sense! regardless of -rc file i would say (perhaps you could override the region from profile in -rc). 

Region is only used by init and init-pipeline commands and unfortunately the aws node sdk has very poor support for reading ~/config files. but will definitely look into it.

**Comment by OlafConijn** [comment]
v0.9.8
