### ISSUE TITLE
org formation support specific CDK stack to deploy  

### ISSUE THREAD

**Issue by lielran** [org-formation/org-formation-cli#482]
it seems that org formation is using --all to deploy all stacks. it would be nice to have a parameter to control on which stack to deploy (with default of all) 
https://github.com/org-formation/org-formation-cli/blob/78f7fbe8c041784757f0afad365cc16e7294b067/src/plugin/impl/cdk-build-task-plugin.ts#L155

**Comment by dannysteenman** [comment]
I've currently solved it for myself by specifying the stack name in the customdeploycommand: 

```
CustomDeployCommand: !Sub AWS_REGION=${AWS::Region} npx cdk deploy --app "ts-node ./src/main.ts" "*gitlab-oidc" --require-approval never
```

**Comment by lielran** [comment]
closed since there is a valid workaround
