### ISSUE TITLE
Clarification DefaultBuildAccessRoleName vs DefaultBuildProcessAccessRoleName

### ISSUE THREAD

**Issue by k-paulius** [org-formation/org-formation-cli#515]
Hi, @OlafConijn, could you please clarify the difference between `DefaultBuildAccessRoleName` and `DefaultBuildProcessAccessRoleName`. Are they essentially the same thing?

`DefaultBuildProcessAccessRoleName` is documented in [organization-resources.md](../blob/master/docs/organization-resources.md). `DefaultBuildAccessRoleName` is used in the generated `organization.yml`, but not documented. And code refers to both properties.

Thanks!

**Comment by OlafConijn** [comment]
thanks for calling this out @k-paulius.

the `DefaultBuildProcessAccessRoleName` in indeed an internal name and should not have appeared in the docs. I fixed this in the following commit: https://github.com/org-formation/org-formation-cli/compare/4d42466db20c...db3ae5ff8d48

**Comment by k-paulius** [comment]
Appreciate you clarifying that @OlafConijn.

This is a bit unrelated, but I also noticed that `TaskViaRoleArn` is not documented. Am I correct in assuming that `TaskViaRoleArn` is assumed before assuming `TaskRoleName` (or `DefaultBuildAccessRoleName` if `TaskRoleName` is not defined).

**Comment by OlafConijn** [comment]
exactly right

**Comment by k-paulius** [comment]
Thanks again @OlafConijn, I submitted pull request to document that.
