### ISSUE TITLE
[Question] Best practices

### ISSUE THREAD

**Issue by hffmnn** [org-formation/org-formation-cli#78]
Hi.

I watched the video at https://www.youtube.com/watch?v=mLAGHzidHJ0 and wonder if there is a collection of best practices or e.g. a baseline for setting up an AWS Organization?

As an example: In your walkthrough, you briefly show the `DenyChangeOfOrgRoleSCP` and the `RestrictUnusedRegionsSCP` `ServiceControlPolicies` which I think are great, but I have not seen them before anywhere else.
I think it would be great to have a "best practices", well-documented template from which to start, which would contain things like:

* SharedUser account
* Development/Infrastructure/Production Accounts
* Best practices for CI/Multi-Account deployments with the help of org-formation
* Deployment only via assume/pass roles to production accounts
* ... endless list continued here

These are all resources that can be found somewhere on the internet and with a bit of luck you stumble over them but with the help of `org-formation` it would be possible, to have everything in one place, bundled in one template.

I know this is a big topic (and every company would like to set this up slightly different), but I guess it would be much better to help new AWS customers with such a template/templates instead of letting them fall into the "everything and everyone in one account" trap.

What do you think? Could that be of interest?

**Comment by OlafConijn** [comment]
i think that would be a great idea!

The SCP's you name, are also part of example that can be found here: https://github.com/OlafConijn/AwsOrganizationFormation/blob/master/examples/organization.yml

But, there is obviously a lot more patterns that can be re-used. Having also worked with org-formation a lot myself it is clear that it is easy to share common patterns & best practices.

I actually recently started with a reference on SSO, which can be found here (still a bit work in progress): https://github.com/OlafConijn/AwsOrganizationFormation/tree/master/examples/sso

Happy to add more, or help others to add their best practices.
Happy to look for the best way to write about and create re-usable templates for these best practices. Perhaps a blogpost + example on github?

let me know! thanks!

**Comment by hffmnn** [comment]
I created a first draft of what a README for `The Slick Startup` might look like https://github.com/hffmnn/AwsOrganizationFormation/pull/1. Feel free to comment or suggest changes.

One thing I found that you are right: Most of the use-cases are already part of the examples and I guess they only need a proper phrasing or a description "why" something is useful and what's the best practice around it.

When I tried to implement the bullet points from the README I came up with one question:

Given I have configured a `DeveloperRole` that has `PowerUserAccess` to all AWS Accounts in the `DevelopmentOU` (exactly the setup you have in your `organizaton.yml`): 

How to generate an actual IAM User for this? Do you do that in code also or is someone responsible for doing that via the console. And what rights should such a user have? I mean: This user has to have some access to the `SharedUsersAccount`, at least to e.g. get the `Programmatic Access` Credentials. Or did I miss something?

Sorry for all these questions. but I'd really like to wrap my head around all of these concepts.

**Comment by OlafConijn** [comment]
hi! 

Very happy with this thread and also your questions. I also feel that there is a lot of value in packaging best practices. i will look at your PR in a bit.

We, in our organization create users in a different system. These users get access to AWS using roles and SSO.  We aim at not having any IAM::User in AWS (unless necessary and if so, low privileged). 

The users in our organization get created/added manually (in that different system) which i think is not a big issue. This can also be done with IAM::Users. A different (arguably better? at least more complex :)) starting point might be a SSO solution. But this indeed might for some organizations be too complex.

**Comment by eduardomourar** [comment]
We have created a new repository with best-practices, patterns and examples that can be used with org-formation: https://github.com/org-formation/org-formation-reference

**Comment by OlafConijn** [comment]
closing per @eduardomourar's comment.
